version: '3.9'
services:
  webapp:
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/src
    networks:
      - frontend
      - backend
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - /mongo:/data/db
    networks:
      - backend
    env_file:
      - .env

networks:
  frontend:
  backend:
